#!/usr/bin/env node
/**
 * login.js — B站扫码登录,自动生成 cookies.txt
 * 流程: 弹二维码 → 手机B站App扫 → 确认 → 自动存 cookies.txt
 * 之后 bili_download.js 直接用这个 cookie 下合集
 *
 * 用法: node login.js
 */
const https = require('https');
const fs = require('fs');
const { execSync } = require('child_process');

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36';
const COOKIE_FILE = process.env.BILI_COOKIE || 'cookies.txt';

function get(url, extra = {}) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': UA, ...extra } }, res => {
      let d = ''; res.on('data', c => d += c);
      res.on('end', () => resolve({ body: d, headers: res.headers }));
    }).on('error', reject);
  });
}
function downloadFile(url, path) {
  return new Promise((resolve, reject) => {
    const f = fs.createWriteStream(path);
    https.get(url, { headers: { 'User-Agent': UA } }, res => {
      res.pipe(f); f.on('finish', () => { f.close(); resolve(); });
    }).on('error', reject);
  });
}
const sleep = ms => new Promise(r => setTimeout(r, ms));

(async () => {
  // 1. 生成二维码
  console.log('获取登录二维码...');
  const gen = JSON.parse((await get('https://passport.bilibili.com/x/passport-login/web/qrcode/generate')).body);
  if (gen.code !== 0) { console.log('❌ 生成失败:', gen.message); process.exit(1); }
  const qrUrl = gen.data.url;
  const qrcodeKey = gen.data.qrcode_key;

  // 2. 生成二维码图片(在线API)并打开
  const imgApi = 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=' + encodeURIComponent(qrUrl);
  const imgPath = '_login_qr.png';
  try {
    await downloadFile(imgApi, imgPath);
    const open = process.platform === 'win32' ? 'start ""'
               : process.platform === 'darwin' ? 'open'
               : 'xdg-open';
    execSync(open + ' "' + imgPath + '"');
    console.log('二维码已弹出,请用【手机B站App】扫描');
  } catch (e) {
    console.log('⚠️ 自动打开二维码失败,请手动扫码。用任意工具把下面URL生成二维码扫:');
    console.log('   ' + qrUrl);
  }
  console.log('   (或直接打开文件: ' + imgPath + ')');

  // 3. 轮询登录状态
  console.log('等待扫码确认(2秒一次,最多2分钟)...');
  let setCookies = [];
  for (let i = 0; i < 60; i++) {
    await sleep(2000);
    const resp = await get('https://passport.bilibili.com/x/passport-login/web/qrcode/poll?qrcode_key=' + qrcodeKey + '&source=main-web',
      { Referer: 'https://www.bilibili.com/' });
    const data = JSON.parse(resp.body).data;
    if (data.code === 0) {
      setCookies = resp.headers['set-cookie'] || [];
      console.log('✅ 登录成功!');
      break;
    } else if (data.code === 86090) {
      process.stdout.write('\r  已扫描,请在手机点确认...   ');
    } else if (data.code === 86038) {
      console.log('\n❌ 二维码过期,请重跑 node login.js'); process.exit(1);
    }
  }
  if (!setCookies.length) { console.log('\n❌ 登录超时'); process.exit(1); }

  // 4. 补 buvid3/buvid4(spi,匿名可拿)
  const spi = JSON.parse((await get('https://api.bilibili.com/x/frontend/finger/spi')).body);
  const extraCookies = ['buvid3=' + spi.data.b_3, 'buvid4=' + spi.data.b_4];

  // 5. 解析所有 set-cookie + buvid → Netscape 格式存盘
  const ATTRS = new Set(['Path', 'Domain', 'Expires', 'Max-Age', 'SameSite', 'Secure', 'HttpOnly', 'expires', 'path', 'domain', 'max-age', 'samesite', 'secure', 'httponly']);
  const pairs = {};   // name -> value
  for (const sc of setCookies) {
    const parts = sc.split(/;\s*/);
    for (const p of parts) {
      const eq = p.indexOf('=');
      if (eq < 0) continue;
      const name = p.slice(0, eq).trim();
      if (ATTRS.has(name)) continue;
      pairs[name] = p.slice(eq + 1).trim();
    }
  }
  for (const p of extraCookies) {
    const [name, ...val] = p.split('=');
    pairs[name] = val.join('=');
  }

  const exp = Math.floor(Date.now() / 1000) + 86400 * 30;
  const lines = ['# Netscape HTTP Cookie File', '# https://curl.haxx.se/rfc/cookie_spec.html', '# Generated by login.js'];
  for (const [name, value] of Object.entries(pairs)) {
    lines.push(['.bilibili.com', 'TRUE', '/', 'FALSE', exp, name, value].join('\t'));
  }
  fs.writeFileSync(COOKIE_FILE, lines.join('\n'));
  try { fs.unlinkSync(imgPath); } catch (e) {}

  console.log('\n✅ cookies.txt 已生成: ' + COOKIE_FILE + ' (' + Object.keys(pairs).length + ' 条,含 SESSDATA+buvid3)');
  console.log('现在可跑: node bili_download.js');
})();
